# -*- coding: utf-8 -*-
# Generated by Django 1.11.18 on 2019-04-01 16:16
from __future__ import unicode_literals

from django.db import migrations

def attach_items_to_default_resume(apps, schema_editor):
    UserModel = apps.get_model('auth','User')
    ResumeModel = apps.get_model('resume','Resume')
    ResumeItemModel = apps.get_model('resume','ResumeItem')

    for person in UserModel.objects.all():
        new_resume = ResumeModel.objects.filter(user=person)[0]
        resumeItems = ResumeItemModel.objects.filter(user=person)
        for item in resumeItems:
            item.resume = new_resume
            item.save()
        

class Migration(migrations.Migration):

    dependencies = [
        ('resume', '0003_auto_20190401_1338'),
    ]

    operations = [
        migrations.RunPython(attach_items_to_default_resume)
    ]
